"""alter menu

Revision ID: 169f18a44e72
Revises: cb8c642a2ee8
Create Date: 2026-06-26 13:37:58.160467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '169f18a44e72'
down_revision: Union[str, Sequence[str], None] = 'cb8c642a2ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_login_log', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='',
               existing_nullable=True)
    op.alter_column('admin_role', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='',
               existing_nullable=False)
    op.alter_column('admin_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='',
               existing_nullable=False)
    op.alter_column('admin_role', 'delete_time',
               existing_type=mysql.DATETIME(),
               comment='',
               existing_nullable=True)
    op.alter_column('menu', 'pid',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='父id')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.alter_column('menu', 'pid',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='父id')
    op.alter_column('admin_role', 'delete_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('admin_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('admin_role', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('admin_login_log', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
