"""menu alter type

Revision ID: 723c3bbc0f0b
Revises: 169f18a44e72
Create Date: 2026-06-29 15:44:18.279354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '723c3bbc0f0b'
down_revision: Union[str, Sequence[str], None] = '169f18a44e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_login_log', 'user_agent',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='',
               existing_nullable=True)
    op.alter_column('admin_role', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='',
               existing_nullable=False)
    op.alter_column('admin_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='',
               existing_nullable=False)
    op.alter_column('admin_role', 'delete_time',
               existing_type=mysql.DATETIME(),
               comment='',
               existing_nullable=True)
    op.alter_column('menu', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=False,
               existing_comment='访问路径')
    op.alter_column('menu', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=False,
               comment='路由名称',
               existing_comment='菜单名称')
    op.alter_column('menu', 'component',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=False,
               existing_comment='组件目录')
    op.alter_column('menu', 'meta',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('menu', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('menu', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('menu', 'sort',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'sort',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('menu', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('menu', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('menu', 'meta',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('menu', 'component',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True,
               existing_comment='组件目录')
    op.alter_column('menu', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True,
               comment='菜单名称',
               existing_comment='路由名称')
    op.alter_column('menu', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True,
               existing_comment='访问路径')
    op.alter_column('admin_role', 'delete_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('admin_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('admin_role', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('admin_login_log', 'user_agent',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
