"""init

Revision ID: 9f7ed0592fd2
Revises: 
Create Date: 2026-06-13 01:27:54.236517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f7ed0592fd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色id'),
    sa.Column('last_login_time', sa.DATETIME(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False, comment='状态 0: 禁用 1:启用'),
    sa.Column('delete_time', sa.DATETIME(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('admin_login_log',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True, comment='管理员id'),
    sa.Column('ip', sa.String(length=30), nullable=True, comment='ip地址'),
    sa.Column('login_time', sa.DATETIME(), nullable=False, comment='登录时间'),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_login_log_id'), 'admin_login_log', ['id'], unique=False)
    op.create_table('admin_role',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('delete_time', sa.DATETIME(), nullable=False, comment='删除时间'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态 0: 禁用 1:启用'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_role_id'), 'admin_role', ['id'], unique=False)
    op.create_table('app_versions',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('package', sa.String(length=225), nullable=True, comment='安装包名'),
    sa.Column('versionCode', sa.Integer(), nullable=False),
    sa.Column('versionName', sa.String(length=50), nullable=True, comment='app版本'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='app图标'),
    sa.Column('compileSdkVersion', sa.String(length=50), nullable=True, comment='编译sdk版本'),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True, comment='平台 android, ios'),
    sa.Column('remark', sa.String(length=225), nullable=True, comment='更新备注'),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False, comment='状态 0: 禁用 1:启用'),
    sa.Column('download_url', sa.String(length=225), nullable=True, comment='下载地址'),
    sa.Column('size', mysql.DOUBLE(asdecimal=True), nullable=True, comment='安装包大小'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_versions_id'), 'app_versions', ['id'], unique=False)
    op.create_table('captcha',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('base64', mysql.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('use_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captcha_id'), 'captcha', ['id'], unique=False)
    op.create_table('menu',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=50), nullable=True, comment='访问路径'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='菜单名称'),
    sa.Column('component', sa.String(length=50), nullable=True, comment='组件目录'),
    sa.Column('redirect', sa.String(length=50), nullable=True, comment='路由重定向'),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True, comment='父id'),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('delete_time', sa.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False, comment='状态 0: 禁用 1:启用'),
    sa.Column('role_ids', sa.String(length=255), nullable=False, comment='角色权限'),
    sa.Column('admin_ids', sa.String(length=255), nullable=False, comment='单个管理员权限'),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_captcha_id'), table_name='captcha')
    op.drop_table('captcha')
    op.drop_index(op.f('ix_app_versions_id'), table_name='app_versions')
    op.drop_table('app_versions')
    op.drop_index(op.f('ix_admin_role_id'), table_name='admin_role')
    op.drop_table('admin_role')
    op.drop_index(op.f('ix_admin_login_log_id'), table_name='admin_login_log')
    op.drop_table('admin_login_log')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
